# Configuração do Prometheus para Plataforma Médico-Educacional
# Roteiros de Dispensação PQT-U
# 
# Este arquivo configura o Prometheus para monitoramento específico
# de uma plataforma educacional médica, com foco em:
# - Métricas de segurança para dados médicos
# - Performance de sistemas de IA médica
# - Conformidade com regulamentações de saúde
# - Alertas específicos para sistemas críticos

global:
  scrape_interval: 15s      # Scrape targets every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  
  # Labels externos aplicados a todas as métricas
  external_labels:
    monitor: 'medical-education-platform'
    environment: 'production'
    compliance: 'LGPD,CFM-2314-2022,ANVISA-RDC-4-2009'

# Configuração de alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Adicionar endpoint do Alertmanager quando configurado
          # - alertmanager:9093

# Carregar regras de alerta
rule_files:
  - "alert_rules_medical.yml"
  # - "recording_rules.yml"

# Configuração de scrape jobs
scrape_configs:
  # Job principal - Backend da aplicação médica
  - job_name: 'roteiro-dispensacao-backend'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/api/metrics/prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    
    # Labels específicos para contexto médico
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'medical_platform_.*'
        target_label: 'medical_system'
        replacement: 'true'
    
    # Configurações de segurança médica
    params:
      format: ['prometheus']
    
    # Headers customizados
    http_sd_configs: []
    
  # Job para métricas do sistema operacional
  - job_name: 'system-metrics'
    static_configs:
      - targets: ['localhost:9100']  # Node Exporter (se disponível)
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Job para métricas de Redis (cache médico)
  - job_name: 'redis-metrics'
    static_configs:
      - targets: ['localhost:9121']  # Redis Exporter (se disponível)
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Job para métricas específicas de IA médica
  - job_name: 'medical-ai-metrics'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/api/metrics/ai'
    scrape_interval: 20s
    scrape_timeout: 15s
    params:
      format: ['json']
    
  # Self-monitoring do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Configurações de armazenamento
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d  # Manter dados por 30 dias
    retention.size: 10GB # Máximo 10GB de dados
    
    # Configurações específicas para dados médicos
    wal-compression: true
    min-block-duration: 2h
    max-block-duration: 25h

# Configurações específicas para plataforma médica
medical_platform_config:
  # Métricas críticas que sempre devem estar disponíveis
  critical_metrics:
    - medical_platform_http_requests_total
    - medical_platform_ai_rag_queries_total
    - medical_platform_dosage_calculations_total
    - medical_platform_security_events_total
    - medical_platform_system_cpu_usage_percent
    - medical_platform_system_memory_usage_percent
    
  # Intervalos de retenção por tipo de métrica
  retention_policies:
    security_events: 90d      # Eventos de segurança - 90 dias
    medical_calculations: 60d  # Cálculos médicos - 60 dias
    system_performance: 30d    # Performance do sistema - 30 dias
    user_interactions: 7d      # Interações do usuário - 7 dias
    
  # Configurações de compliance médico
  compliance:
    lgpd:
      data_retention: 60d
      anonymization: true
      audit_logging: true
    medical_safety:
      alert_on_calculation_errors: true
      monitor_persona_consistency: true
      track_medical_disclaimers: true

# Configurações de web console
web:
  console.templates: /usr/share/prometheus/consoles
  console.libraries: /usr/share/prometheus/console_libraries
  
  # Configurações específicas para ambiente médico
  external-url: http://localhost:9090
  route-prefix: /
  
  # Headers de segurança para compliance médico
  header:
    X-Medical-Platform: "Roteiros-Dispensacao-PQT"
    X-Compliance: "LGPD,CFM-2314-2022"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"

# Configurações de logging
log:
  level: info
  format: json
  
  # Logs específicos para auditoria médica
  audit:
    enabled: true
    file: /var/log/prometheus/audit.log
    retention: 90d