/**
 * Base de palavras-chave para análise de sentimento
 * Focado no contexto de saúde e hanseníase
 */

interface KeywordEntry {
  word: string;
  weight: number; // -1 a 1
}

export const sentimentKeywords = {
  // Palavras positivas
  positive: [
    { word: 'obrigado', weight: 0.8 },
    { word: 'obrigada', weight: 0.8 },
    { word: 'agradecido', weight: 0.8 },
    { word: 'agradecida', weight: 0.8 },
    { word: 'gratidão', weight: 0.9 },
    { word: 'excelente', weight: 0.9 },
    { word: 'ótimo', weight: 0.8 },
    { word: 'ótima', weight: 0.8 },
    { word: 'bom', weight: 0.6 },
    { word: 'boa', weight: 0.6 },
    { word: 'melhor', weight: 0.7 },
    { word: 'melhora', weight: 0.7 },
    { word: 'melhorando', weight: 0.7 },
    { word: 'aliviado', weight: 0.8 },
    { word: 'aliviada', weight: 0.8 },
    { word: 'alívio', weight: 0.7 },
    { word: 'feliz', weight: 0.8 },
    { word: 'contente', weight: 0.7 },
    { word: 'satisfeito', weight: 0.7 },
    { word: 'satisfeita', weight: 0.7 },
    { word: 'compreendi', weight: 0.6 },
    { word: 'entendi', weight: 0.6 },
    { word: 'claro', weight: 0.5 },
    { word: 'clara', weight: 0.5 },
    { word: 'esclarecido', weight: 0.7 },
    { word: 'esclarecida', weight: 0.7 },
    { word: 'ajudou', weight: 0.7 },
    { word: 'útil', weight: 0.6 },
    { word: 'esperança', weight: 0.8 },
    { word: 'confiante', weight: 0.7 },
    { word: 'confiança', weight: 0.7 },
    { word: 'tranquilo', weight: 0.7 },
    { word: 'tranquila', weight: 0.7 },
    { word: 'calmo', weight: 0.6 },
    { word: 'calma', weight: 0.6 },
  ] as KeywordEntry[],
  
  // Palavras negativas - ansiedade/medo
  anxious: [
    { word: 'medo', weight: -0.8 },
    { word: 'assustado', weight: -0.8 },
    { word: 'assustada', weight: -0.8 },
    { word: 'preocupado', weight: -0.7 },
    { word: 'preocupada', weight: -0.7 },
    { word: 'preocupação', weight: -0.7 },
    { word: 'ansioso', weight: -0.8 },
    { word: 'ansiosa', weight: -0.8 },
    { word: 'ansiedade', weight: -0.8 },
    { word: 'nervoso', weight: -0.7 },
    { word: 'nervosa', weight: -0.7 },
    { word: 'tenso', weight: -0.7 },
    { word: 'tensa', weight: -0.7 },
    { word: 'urgente', weight: -0.6 },
    { word: 'urgência', weight: -0.6 },
    { word: 'rápido', weight: -0.5 },
    { word: 'depressa', weight: -0.5 },
    { word: 'agora', weight: -0.4 },
    { word: 'imediato', weight: -0.5 },
    { word: 'grave', weight: -0.8 },
    { word: 'sério', weight: -0.6 },
    { word: 'perigoso', weight: -0.9 },
    { word: 'perigo', weight: -0.9 },
    { word: 'risco', weight: -0.7 },
    { word: 'piorou', weight: -0.8 },
    { word: 'piorando', weight: -0.8 },
    { word: 'piora', weight: -0.8 },
    { word: 'morte', weight: -0.9 },
    { word: 'morrer', weight: -0.9 },
    { word: 'morrendo', weight: -0.9 },
  ] as KeywordEntry[],
  
  // Palavras negativas - frustração
  frustrated: [
    { word: 'irritado', weight: -0.8 },
    { word: 'irritada', weight: -0.8 },
    { word: 'frustrado', weight: -0.8 },
    { word: 'frustrada', weight: -0.8 },
    { word: 'frustração', weight: -0.8 },
    { word: 'chateado', weight: -0.7 },
    { word: 'chateada', weight: -0.7 },
    { word: 'decepcionado', weight: -0.7 },
    { word: 'decepcionada', weight: -0.7 },
    { word: 'decepção', weight: -0.7 },
    { word: 'difícil', weight: -0.5 },
    { word: 'complicado', weight: -0.5 },
    { word: 'complicada', weight: -0.5 },
    { word: 'confuso', weight: -0.6 },
    { word: 'confusa', weight: -0.6 },
    { word: 'confusão', weight: -0.6 },
    { word: 'perdido', weight: -0.7 },
    { word: 'perdida', weight: -0.7 },
    { word: 'desisto', weight: -0.9 },
    { word: 'desistir', weight: -0.9 },
    { word: 'cansado', weight: -0.6 },
    { word: 'cansada', weight: -0.6 },
    { word: 'exausto', weight: -0.7 },
    { word: 'exausta', weight: -0.7 },
    { word: 'impossível', weight: -0.8 },
    { word: 'inútil', weight: -0.8 },
    { word: 'péssimo', weight: -0.9 },
    { word: 'péssima', weight: -0.9 },
    { word: 'horrível', weight: -0.9 },
    { word: 'terrível', weight: -0.9 },
  ] as KeywordEntry[],
  
  // Palavras de dúvida/incerteza
  concerned: [
    { word: 'dúvida', weight: -0.3 },
    { word: 'dúvidas', weight: -0.3 },
    { word: 'será', weight: -0.2 },
    { word: 'talvez', weight: -0.2 },
    { word: 'acho', weight: -0.2 },
    { word: 'incerto', weight: -0.4 },
    { word: 'incerta', weight: -0.4 },
    { word: 'incerteza', weight: -0.4 },
    { word: 'inseguro', weight: -0.5 },
    { word: 'insegura', weight: -0.5 },
    { word: 'insegurança', weight: -0.5 },
    { word: 'estranho', weight: -0.4 },
    { word: 'estranha', weight: -0.4 },
    { word: 'diferente', weight: -0.2 },
    { word: 'mudança', weight: -0.3 },
    { word: 'mudou', weight: -0.3 },
    { word: 'alteração', weight: -0.3 },
    { word: 'sintoma', weight: -0.4 },
    { word: 'sintomas', weight: -0.4 },
    { word: 'sinto', weight: -0.3 },
    { word: 'sentindo', weight: -0.3 },
    { word: 'normal', weight: -0.2 }, // "isso é normal?"
    { word: 'certo', weight: -0.2 }, // "está certo?"
    { word: 'correto', weight: -0.2 }, // "é correto?"
  ] as KeywordEntry[],
  
  // Palavras específicas de saúde/hanseníase
  healthSpecific: [
    { word: 'mancha', weight: -0.4 },
    { word: 'manchas', weight: -0.4 },
    { word: 'dormência', weight: -0.5 },
    { word: 'dormência', weight: -0.5 },
    { word: 'formigamento', weight: -0.4 },
    { word: 'dor', weight: -0.6 },
    { word: 'dores', weight: -0.6 },
    { word: 'doendo', weight: -0.6 },
    { word: 'doloroso', weight: -0.6 },
    { word: 'dolorosa', weight: -0.6 },
    { word: 'inchaço', weight: -0.5 },
    { word: 'inchado', weight: -0.5 },
    { word: 'inchada', weight: -0.5 },
    { word: 'reação', weight: -0.6 },
    { word: 'reações', weight: -0.6 },
    { word: 'efeito', weight: -0.4 },
    { word: 'efeitos', weight: -0.4 },
    { word: 'colateral', weight: -0.5 },
    { word: 'colaterais', weight: -0.5 },
    { word: 'remédio', weight: -0.2 },
    { word: 'remédios', weight: -0.2 },
    { word: 'medicamento', weight: -0.2 },
    { word: 'medicamentos', weight: -0.2 },
    { word: 'tratamento', weight: -0.1 },
    { word: 'cura', weight: 0.6 }, // positivo no contexto
    { word: 'curado', weight: 0.7 },
    { word: 'curada', weight: 0.7 },
    { word: 'melhorou', weight: 0.7 },
    { word: 'sumiu', weight: 0.6 }, // "a mancha sumiu"
    { word: 'desapareceu', weight: 0.6 },
  ] as KeywordEntry[],
  
  // Intensificadores (multiplicam o peso da palavra anterior/próxima)
  intensifiers: [
    { word: 'muito', weight: 1.5 },
    { word: 'muita', weight: 1.5 },
    { word: 'demais', weight: 1.8 },
    { word: 'extremamente', weight: 2.0 },
    { word: 'super', weight: 1.7 },
    { word: 'bastante', weight: 1.4 },
    { word: 'bem', weight: 1.3 },
    { word: 'pouco', weight: 0.6 },
    { word: 'pouca', weight: 0.6 },
    { word: 'um pouco', weight: 0.7 },
    { word: 'mais ou menos', weight: 0.5 },
    { word: 'não', weight: -1.0 }, // inverte o sentimento
    { word: 'nem', weight: -0.8 },
    { word: 'nunca', weight: -1.2 },
    { word: 'sempre', weight: 1.3 },
  ] as KeywordEntry[],
};