#!/bin/bash
# Script para adicionar GitHub Secrets a partir dos arquivos .env
# Execução: bash scripts/add_github_secrets.sh

REPO="AnalineS/roteirosdedispersacao"

echo "🔐 Iniciando adição de GitHub Secrets..."
echo "📦 Repositório: $REPO"
echo ""

# Função para adicionar secret
add_secret() {
    local name=$1
    local value=$2
    echo "➕ Adicionando: $name"
    echo "$value" | gh secret set "$name" --repo "$REPO"
}

# ===================================
# SECRETS COMPARTILHADOS
# ===================================
echo "📋 Adicionando Secrets Compartilhados..."

add_secret "MEDICAL_CONTENT_VERSION" "2024.1"
add_secret "PCDT_VERSION" "2022"
add_secret "MEDICAL_DISCLAIMER_ENABLED" "true"
add_secret "AI_PROVIDER_TIMEOUT" "30"
add_secret "AI_PROVIDER_MAX_RETRIES" "3"
add_secret "AI_CIRCUIT_BREAKER_ENABLED" "true"
add_secret "SECURITY_HEADERS_ENABLED" "true"
add_secret "CSP_ENABLED" "true"
add_secret "HSTS_ENABLED" "true"
add_secret "X_FRAME_OPTIONS" "DENY"
add_secret "X_CONTENT_TYPE_OPTIONS" "nosniff"
add_secret "OPENAPI_ENABLED" "true"
add_secret "SWAGGER_UI_ENABLED" "true"
add_secret "REDOC_ENABLED" "true"
add_secret "DR_GASNELIO_ENABLED" "true"
add_secret "GA_ENABLED" "true"
add_secret "PERSONA_VALIDATION_ENABLED" "true"
add_secret "KNOWLEDGE_BASE_VERSION" "1.0"
add_secret "STRUCTURED_DATA_ENABLED" "true"
add_secret "RAG_ENABLED" "true"
add_secret "EMAIL_SENDER_NAME" "Roteiro de Dispensação"
add_secret "EMAIL_TEMPLATE_VERSION" "1.0"
add_secret "TELEGRAM_ENABLED" "true"
add_secret "TELEGRAM_PARSE_MODE" "Markdown"
add_secret "LGPD_COMPLIANCE_ENABLED" "true"
add_secret "AUDIT_LOGGING_ENABLED" "true"
add_secret "DATA_RETENTION_DAYS" "90"
add_secret "DEFAULT_LANGUAGE" "pt-BR"
add_secret "SUPPORTED_LANGUAGES" "pt-BR"
add_secret "TIMEZONE" "America/Sao_Paulo"
add_secret "MEDICAL_VALIDATION_ENABLED" "true"
add_secret "SCOPE_DETECTION_ENABLED" "true"
add_secret "DISCLAIMER_REQUIRED" "true"
add_secret "PERFORMANCE_MONITORING_ENABLED" "true"
add_secret "UPTIME_MONITORING_ENABLED" "true"
add_secret "ERROR_TRACKING_ENABLED" "true"

# ===================================
# SECRETS DE HOMOLOGAÇÃO (HML)
# ===================================
echo ""
echo "🧪 Adicionando Secrets de Homologação..."

add_secret "HML_ENVIRONMENT" "homologacao"
add_secret "HML_FLASK_ENV" "production"
add_secret "HML_DEBUG" "false"
add_secret "HML_PORT" "8080"
add_secret "HML_HOST" "0.0.0.0"
add_secret "HML_FIRESTORE_COLLECTION_PREFIX" "hml_"
add_secret "HML_API_VERSION" "v1"
add_secret "HML_API_TITLE" "Roteiro Dispensação API - HML"
add_secret "HML_API_DESCRIPTION" "Sistema educacional para dispensação farmacêutica - Ambiente de Homologação"
add_secret "HML_CORS_ORIGINS" "https://hml-roteiros-de-dispensacao.web.app,https://hml-roteiros-de-dispensacao.firebaseapp.com"
add_secret "HML_CACHE_TTL" "300"
add_secret "HML_CACHE_MAX_SIZE" "100"
add_secret "HML_RATE_LIMIT_ENABLED" "true"
add_secret "HML_RATE_LIMIT_PER_MINUTE" "120"
add_secret "HML_LOG_LEVEL" "INFO"
add_secret "HML_LOG_FORMAT" "json"
add_secret "HML_STRUCTURED_LOGGING" "true"
add_secret "HML_HEALTH_CHECK_TIMEOUT" "30"
add_secret "HML_HEALTH_CHECK_ENDPOINT" "/health"
add_secret "HML_ENABLE_TEST_ENDPOINTS" "true"
add_secret "HML_RESET_DATA_ON_DEPLOY" "true"
add_secret "HML_SYNTHETIC_DATA_ENABLED" "true"
add_secret "HML_MONITORING_ENABLED" "true"
add_secret "HML_METRICS_ENABLED" "true"
add_secret "HML_ALERT_ENVIRONMENT" "hml"
add_secret "HML_SECURITY_LEVEL" "standard"
add_secret "HML_RATE_LIMIT_STRICT" "false"
add_secret "HML_CORS_ALLOW_CREDENTIALS" "false"
add_secret "HML_WORKERS" "2"
add_secret "HML_THREADS" "4"
add_secret "HML_TIMEOUT" "120"
add_secret "HML_KEEP_ALIVE" "2"
add_secret "HML_MAX_REQUESTS" "1000"
add_secret "HML_ENABLE_EXPERIMENTAL_FEATURES" "true"
add_secret "HML_ENABLE_DEBUG_ENDPOINTS" "true"
add_secret "HML_ENABLE_PERFORMANCE_PROFILING" "true"

# Serviços Avançados HML
add_secret "HML_SUPABASE_ENABLED" "true"
add_secret "HML_EMBEDDINGS_ENABLED" "true"
add_secret "HML_RAG_AVAILABLE" "true"
add_secret "HML_VECTOR_DB_TYPE" "supabase"
add_secret "HML_SECURITY_MIDDLEWARE_ENABLED" "true"
add_secret "HML_FIRESTORE_CACHE_ENABLED" "true"
add_secret "HML_HYBRID_CACHE_STRATEGY" "memory_first"
add_secret "HML_ADVANCED_FEATURES" "true"
add_secret "HML_EMBEDDING_MODEL" "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
add_secret "HML_EMBEDDING_DEVICE" "cpu"
add_secret "HML_EMBEDDINGS_MAX_LENGTH" "512"
add_secret "HML_EMBEDDING_BATCH_SIZE" "32"
add_secret "HML_SEMANTIC_SIMILARITY_THRESHOLD" "0.7"
add_secret "HML_PGVECTOR_DIMENSIONS" "384"

# ===================================
# SECRETS DE PRODUÇÃO (PROD)
# ===================================
echo ""
echo "🚀 Adicionando Secrets de Produção..."

add_secret "PROD_ENVIRONMENT" "production"
add_secret "PROD_FLASK_ENV" "production"
add_secret "PROD_DEBUG" "false"
add_secret "PROD_PORT" "8080"
add_secret "PROD_HOST" "0.0.0.0"
add_secret "PROD_FIRESTORE_COLLECTION_PREFIX" "prod_"
add_secret "PROD_API_VERSION" "v1"
add_secret "PROD_API_TITLE" "Roteiro Dispensação API"
add_secret "PROD_API_DESCRIPTION" "Sistema educacional para dispensação farmacêutica"
add_secret "PROD_CORS_ORIGINS" "https://roteiros-de-dispensacao.web.app,https://roteiros-de-dispensacao.firebaseapp.com"
add_secret "PROD_CACHE_TTL" "3600"
add_secret "PROD_CACHE_MAX_SIZE" "500"
add_secret "PROD_RATE_LIMIT_ENABLED" "true"
add_secret "PROD_RATE_LIMIT_PER_MINUTE" "60"
add_secret "PROD_LOG_LEVEL" "WARNING"
add_secret "PROD_LOG_FORMAT" "json"
add_secret "PROD_STRUCTURED_LOGGING" "true"
add_secret "PROD_HEALTH_CHECK_TIMEOUT" "15"
add_secret "PROD_HEALTH_CHECK_ENDPOINT" "/health"
add_secret "PROD_ENABLE_TEST_ENDPOINTS" "false"
add_secret "PROD_RESET_DATA_ON_DEPLOY" "false"
add_secret "PROD_SYNTHETIC_DATA_ENABLED" "false"
add_secret "PROD_MONITORING_ENABLED" "true"
add_secret "PROD_METRICS_ENABLED" "true"
add_secret "PROD_ALERT_ENVIRONMENT" "production"
add_secret "PROD_SECURITY_LEVEL" "strict"
add_secret "PROD_RATE_LIMIT_STRICT" "true"
add_secret "PROD_CORS_ALLOW_CREDENTIALS" "false"
add_secret "PROD_WORKERS" "4"
add_secret "PROD_THREADS" "8"
add_secret "PROD_TIMEOUT" "60"
add_secret "PROD_KEEP_ALIVE" "5"
add_secret "PROD_MAX_REQUESTS" "5000"
add_secret "PROD_ENABLE_EXPERIMENTAL_FEATURES" "false"
add_secret "PROD_ENABLE_DEBUG_ENDPOINTS" "false"
add_secret "PROD_ENABLE_PERFORMANCE_PROFILING" "false"

# Serviços Avançados PROD
add_secret "PROD_SUPABASE_ENABLED" "true"
add_secret "PROD_EMBEDDINGS_ENABLED" "true"
add_secret "PROD_RAG_AVAILABLE" "true"
add_secret "PROD_VECTOR_DB_TYPE" "supabase"
add_secret "PROD_SECURITY_MIDDLEWARE_ENABLED" "true"
add_secret "PROD_FIRESTORE_CACHE_ENABLED" "true"
add_secret "PROD_HYBRID_CACHE_STRATEGY" "memory_first"
add_secret "PROD_ADVANCED_FEATURES" "true"
add_secret "PROD_EMBEDDING_MODEL" "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
add_secret "PROD_EMBEDDING_DEVICE" "cpu"
add_secret "PROD_EMBEDDINGS_MAX_LENGTH" "512"
add_secret "PROD_EMBEDDING_BATCH_SIZE" "64"
add_secret "PROD_SEMANTIC_SIMILARITY_THRESHOLD" "0.75"
add_secret "PROD_PGVECTOR_DIMENSIONS" "384"

echo ""
echo "✅ Processo concluído!"
echo "📊 Total de secrets adicionados: ~120"
echo ""
echo "⚠️  IMPORTANTE:"
echo "1. Verifique se os secrets foram adicionados corretamente:"
echo "   gh secret list --repo $REPO | wc -l"
echo ""
echo "2. Alguns secrets sensíveis já devem estar configurados:"
echo "   - OPENROUTER_API_KEY"
echo "   - HUGGINGFACE_API_KEY"
echo "   - FIREBASE_PROJECT_ID"
echo "   - SUPABASE_* (8 secrets)"
echo ""
echo "3. Depois de verificar, exclua os arquivos .env:"
echo "   rm -rf environments/"