name: "[BOT] Dependabot Manager (Unificado)"

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main, hml]
  push:
    branches: [dependabot-updates, main, hml]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Tipo de release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - hotfix

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze-dependabot-pr:
    name: "[ANALYZE] Analisar PR do Dependabot"
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'homologacao' }}
    
    outputs:
      update-type: ${{ steps.analyze.outputs.update_type }}
      should-auto-merge: ${{ steps.analyze.outputs.should_auto_merge }}
    
    steps:
      - name: "[CHECKOUT] Checkout"
        uses: actions/checkout@v4
        
      - name: "[ANALYZE] Analisar Detalhes do PR"
        id: analyze
        run: |
          echo "[ANALYZE] Analisando PR do Dependabot no ambiente: $ENVIRONMENT"
          echo "[ANALYZE] Branch de destino: ${{ github.base_ref }}"
          
          UPDATE_TYPE="patch"
          SHOULD_AUTO_MERGE=false
          
          if [[ "${{ github.event.pull_request.title }}" == *"security"* ]]; then
            UPDATE_TYPE="security"
            SHOULD_AUTO_MERGE=true
            echo "[LOCK] Atualizacao de SEGURANCA detectada para $ENVIRONMENT"
          elif [[ "${{ github.event.pull_request.title }}" == *"patch"* ]]; then
            UPDATE_TYPE="patch"
            SHOULD_AUTO_MERGE=true
            echo "[TOOLS] Atualizacao PATCH detectada para $ENVIRONMENT"
          fi
          
          echo "update_type=$UPDATE_TYPE" >> $GITHUB_OUTPUT
          echo "should_auto_merge=$SHOULD_AUTO_MERGE" >> $GITHUB_OUTPUT

  auto-merge-handler:
    name: "[PROCESS] Gerenciar Auto-merge"
    runs-on: ubuntu-latest
    needs: analyze-dependabot-pr
    if: needs.analyze-dependabot-pr.outputs.should-auto-merge == 'true'
    
    steps:
      - name: "[OK] Auto-aprovar com Justificativa"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'homologacao' }}
        run: |
          echo "[OK] Auto-aprovando PR com justificativa no ambiente $ENVIRONMENT..."
          gh pr review --approve "${{ github.event.pull_request.html_url }}" --body "[OK] Aprovacao automatica aplicada para $ENVIRONMENT"

      - name: "[DEPLOY] Habilitar Auto-merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'homologacao' }}
        run: |
          echo "[DEPLOY] Habilitando auto-merge para $ENVIRONMENT..."
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"

concurrency:
  group: dependabot-manager-${{ github.ref }}
  cancel-in-progress: false