name: 🤖 Dependabot Helper

on:
  pull_request:
    types: [opened, reopened, synchronize]
    # Manter TODAS as execuções para segurança e qualidade
    # Apenas otimizar condicionais para reduzir trabalho redundante

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-merge:
    name: 🔄 Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        
      - name: 🔍 Check PR Details
        id: pr-check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "📋 PR Title: $PR_TITLE"
          
          # Determine update type
          if [[ "$PR_TITLE" == *"patch"* ]] || [[ "$PR_TITLE" == *"security"* ]]; then
            echo "type=patch" >> $GITHUB_OUTPUT
            echo "✅ Patch/Security update detected - will auto-merge"
          elif [[ "$PR_TITLE" == *"minor"* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
            echo "⚠️ Minor update detected - needs review"
          elif [[ "$PR_TITLE" == *"major"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
            echo "🚨 Major update detected - manual review required"
          else
            echo "type=unknown" >> $GITHUB_OUTPUT
            echo "❓ Unknown update type"
          fi
          
      - name: 🏷️ Add Labels
        uses: actions/labeler@v4
        with:
          configuration-path: |
            dependencies:
              - any: ['**']
            ${{ steps.pr-check.outputs.type }}:
              - any: ['**']
            auto-merge:
              - any: ['**']
        continue-on-error: true
        
      - name: ✅ Auto-approve Patches
        if: steps.pr-check.outputs.type == 'patch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
          echo "✅ PR approved automatically"
          
      - name: 🔄 Enable Auto-merge for Patches
        if: steps.pr-check.outputs.type == 'patch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
          echo "🔄 Auto-merge enabled - will merge when checks pass"
          
      - name: 💬 Comment on Minor Updates
        if: steps.pr-check.outputs.type == 'minor'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.html_url }}" \
            --body "⚠️ **Minor version update detected**
            
            This PR updates to a new minor version. Please review:
            - Check the changelog for new features
            - Verify no breaking changes in minor version
            - Run tests locally if needed
            
            After review, merge manually or approve for auto-merge."
            
      - name: 🚨 Comment on Major Updates
        if: steps.pr-check.outputs.type == 'major'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.html_url }}" \
            --body "🚨 **Major version update detected**
            
            This PR contains breaking changes. Required actions:
            1. Review the migration guide
            2. Update code to handle breaking changes
            3. Test thoroughly in development
            4. Update documentation if needed
            
            **Do not auto-merge - manual review required!**"

  check-duplicates:
    name: 🔍 Check for Duplicate PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: 🔍 Find Duplicate PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get package name from PR title
          PACKAGE=$(echo "${{ github.event.pull_request.title }}" | sed -n 's/.*bump \(.*\) from.*/\1/p')
          
          if [ -n "$PACKAGE" ]; then
            echo "📦 Checking for duplicates of: $PACKAGE"
            
            # List all open PRs for this package
            DUPLICATES=$(gh pr list --author app/dependabot --state open --search "$PACKAGE" --json number,title)
            
            COUNT=$(echo "$DUPLICATES" | jq length)
            if [ "$COUNT" -gt 1 ]; then
              echo "⚠️ Found $COUNT PRs for $PACKAGE"
              
              # Comment on PR about duplicates
              gh pr comment "${{ github.event.pull_request.html_url }}" \
                --body "⚠️ **Duplicate PRs detected**
                
                Found multiple PRs for $PACKAGE. Consider closing older ones:
                \`\`\`
                $DUPLICATES
                \`\`\`"
            fi
          fi

  security-check:
    name: 🔒 Additional Security Checks
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        
      - name: 🔍 Check for Known Vulnerabilities
        run: |
          # Extract package and version info
          TITLE="${{ github.event.pull_request.title }}"
          
          # Check if it's a security update
          if [[ "$TITLE" == *"security"* ]] || [[ "${{ github.event.pull_request.body }}" == *"vulnerability"* ]]; then
            echo "🔒 Security update detected - prioritizing merge"
            
            # Add security label
            gh pr edit "${{ github.event.pull_request.html_url }}" \
              --add-label "security,priority:high"
              
            # Request immediate review
            gh pr comment "${{ github.event.pull_request.html_url }}" \
              --body "🔒 **Security Update - Priority Review Required**
              
              This PR addresses security vulnerabilities. 
              Recommended action: Review and merge ASAP.
              
              Auto-merge has been enabled for faster deployment."
              
            # Enable auto-merge regardless of version
            gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}