name: "[LABELS] Sistema de Labels Automáticos"

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [main, hml]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Número do PR para re-aplicar labels'
        required: true
        type: number

permissions:
  contents: read
  pull-requests: write
  issues: write

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  apply-labels:
    name: "[APPLY] Aplicar Labels Automáticos" 
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    
    outputs:
      labels-applied: ${{ steps.labeler.outputs.labels-applied }}
      
    steps:
      - name: "[CHECKOUT] Checkout"
        uses: actions/checkout@v4
        
      - name: "[LABELS] Aplicar Labels v5"
        id: labeler
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'
          sync-labels: true
          dot: true
          
      - name: "[ANALYSIS] Analisar Labels Aplicados"
        id: analysis
        env:
          PR_NUMBER: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}
        run: |
          echo "Analisando labels aplicados ao PR #$PR_NUMBER..."
          
          # Buscar labels do PR via API
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')
          
          # Análise de prioridade
          PRIORITY="baixa"
          if echo "$LABELS" | grep -q "prioridade: crítica"; then
            PRIORITY="crítica" 
          elif echo "$LABELS" | grep -q "prioridade: alta"; then
            PRIORITY="alta"
          elif echo "$LABELS" | grep -q "prioridade: média"; then
            PRIORITY="média"
          fi
          
          # Análise de tipo
          TYPE="geral"
          if echo "$LABELS" | grep -q "tipo: hotfix"; then
            TYPE="hotfix"
          elif echo "$LABELS" | grep -q "tipo: bugfix"; then
            TYPE="correção"
          elif echo "$LABELS" | grep -q "tipo: feature"; then
            TYPE="funcionalidade"
          elif echo "$LABELS" | grep -q "breaking-change"; then
            TYPE="breaking-change"
          fi
          
          # Análise de área
          AREAS=""
          if echo "$LABELS" | grep -q "área: backend"; then
            AREAS="$AREAS Backend"
          fi
          if echo "$LABELS" | grep -q "área: frontend"; then
            AREAS="$AREAS Frontend"
          fi
          if echo "$LABELS" | grep -q "área: ci-cd"; then
            AREAS="$AREAS CI/CD"
          fi
          
          # Análise de ambiente
          ENVIRONMENT="indefinido"
          if echo "$LABELS" | grep -q "ambiente: produção"; then
            ENVIRONMENT="produção"
          elif echo "$LABELS" | grep -q "ambiente: homologação"; then
            ENVIRONMENT="homologação"
          fi
          
          echo "priority=$PRIORITY" >> $GITHUB_OUTPUT
          echo "type=$TYPE" >> $GITHUB_OUTPUT
          echo "areas=$AREAS" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "all_labels=$LABELS" >> $GITHUB_OUTPUT
          
          echo "Análise concluída:"
          echo "- Prioridade: $PRIORITY"
          echo "- Tipo: $TYPE" 
          echo "- Áreas: $AREAS"
          echo "- Ambiente: $ENVIRONMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-critical-prs:
    name: "[VALIDATE] Validar PRs Críticos"
    runs-on: ubuntu-latest
    needs: apply-labels
    if: >
      contains(needs.apply-labels.outputs.all_labels, 'prioridade: crítica') ||
      contains(needs.apply-labels.outputs.all_labels, 'breaking-change')
    
    steps:
      - name: "[CHECKOUT] Checkout"
        uses: actions/checkout@v4
        
      - name: "[VALIDATE] Validação Adicional para PRs Críticos"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PRIORITY: ${{ needs.apply-labels.outputs.priority }}
          TYPE: ${{ needs.apply-labels.outputs.type }}
        run: |
          echo "Executando validações adicionais para PR crítico #$PR_NUMBER..."
          
          # Verificar se PR tem descrição adequada
          DESCRIPTION=$(gh pr view $PR_NUMBER --json body --jq '.body')
          if [ ${#DESCRIPTION} -lt 50 ]; then
            echo "⚠️ AVISO: PR crítico com descrição muito curta"
            gh pr comment $PR_NUMBER --body "⚠️ **PR Crítico Detectado** 
            
Este PR foi marcado como **$PRIORITY** e tipo **$TYPE**.
            
**Ações Necessárias:**
- [ ] Descrição detalhada dos changes
- [ ] Evidências de teste
- [ ] Revisão obrigatória de pelo menos 2 pessoas
- [ ] Aprovação do tech lead antes do merge

**Labels aplicados:** ${{ needs.apply-labels.outputs.all_labels }}"
          fi
          
          # Adicionar reviewers para PRs críticos
          if [ "$PRIORITY" = "crítica" ]; then
            echo "Adicionando reviewers obrigatórios para PR crítico..."
            gh pr edit $PR_NUMBER --add-reviewer "AnalineS"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-labeling:
    name: "[NOTIFY] Notificar Resultado do Labeling"
    runs-on: ubuntu-latest
    needs: [apply-labels, validate-critical-prs]
    if: always() && needs.apply-labels.result == 'success'
    
    steps:
      - name: "[NOTIFY] Telegram - Labels Aplicados"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          PR_TITLE: ${{ github.event.pull_request.title || 'PR Manual' }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login || github.actor }}
          PRIORITY: ${{ needs.apply-labels.outputs.priority }}
          TYPE: ${{ needs.apply-labels.outputs.type }}
          AREAS: ${{ needs.apply-labels.outputs.areas }}
          ENVIRONMENT: ${{ needs.apply-labels.outputs.environment }}
        run: |
          # Determinar emoji baseado na prioridade
          if [ "$PRIORITY" = "crítica" ]; then
            EMOJI="🚨"
            STATUS_MSG="CRÍTICO"
          elif [ "$PRIORITY" = "alta" ]; then
            EMOJI="⚡"
            STATUS_MSG="ALTA PRIORIDADE" 
          elif [ "$PRIORITY" = "média" ]; then
            EMOJI="📋"
            STATUS_MSG="PRIORIDADE MÉDIA"
          else
            EMOJI="📝"
            STATUS_MSG="BAIXA PRIORIDADE"
          fi
          
          # Montar mensagem
          MESSAGE="$EMOJI **PR $STATUS_MSG** - #$PR_NUMBER"
          MESSAGE="$MESSAGE%0A%0A**Título:** $PR_TITLE"
          MESSAGE="$MESSAGE%0A**Autor:** $PR_AUTHOR"
          MESSAGE="$MESSAGE%0A**Tipo:** $TYPE"
          MESSAGE="$MESSAGE%0A**Áreas:** $AREAS"
          MESSAGE="$MESSAGE%0A**Ambiente:** $ENVIRONMENT"
          MESSAGE="$MESSAGE%0A**Prioridade:** $PRIORITY"
          
          if [ "$PRIORITY" = "crítica" ]; then
            MESSAGE="$MESSAGE%0A%0A⚠️ **ATENÇÃO: Revisão obrigatória necessária**"
          fi
          
          MESSAGE="$MESSAGE%0A%0A[Ver PR](https://github.com/${{ github.repository }}/pull/$PR_NUMBER)"
          
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode="Markdown"

  update-dependabot-labels:
    name: "[UPDATE] Labels Específicos do Dependabot"
    runs-on: ubuntu-latest
    needs: apply-labels
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: "[DEPENDABOT] Labels Específicos"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Aplicando labels específicos do Dependabot..."
          
          # Determinar ambiente baseado na branch base
          if [ "${{ github.base_ref }}" = "main" ]; then
            AMBIENTE="prod"
          else
            AMBIENTE="hml"
          fi
          
          # Determinar impacto baseado no título
          IMPACT="baixo"
          if echo "$PR_TITLE" | grep -q -i "security\|vulnerability"; then
            IMPACT="crítico"
            gh pr edit $PR_NUMBER --add-label "impacto: crítico"
            gh pr edit $PR_NUMBER --add-label "security"
          elif echo "$PR_TITLE" | grep -q -i "major"; then
            IMPACT="alto"
            gh pr edit $PR_NUMBER --add-label "impacto: alto"
          else
            gh pr edit $PR_NUMBER --add-label "impacto: baixo"
          fi
          
          # Adicionar label de ambiente Dependabot
          gh pr edit $PR_NUMBER --add-label "dependabot: $AMBIENTE"
          
          echo "Labels do Dependabot aplicados: impacto $IMPACT, ambiente $AMBIENTE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: pr-labeler-${{ github.event.pull_request.number || github.event.inputs.pr_number }}
  cancel-in-progress: true