name: "Validacao de Unicode"

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Verificar caracteres Unicode invalidos"
        run: |
          echo "Verificando arquivos YAML para problemas de Unicode..."
          
          for file in .github/workflows/*.yml .github/workflows/*.yaml; do
            if [ -f "$file" ]; then
              # Verifica surrogates UTF-16 orfaos
              if grep -P '[\x{D800}-\x{DFFF}]' "$file" > /dev/null 2>&1; then
                echo "ERRO: $file contem caracteres Unicode invalidos"
                exit 1
              fi
              
              # Valida sintaxe YAML
              python3 -c "import yaml; yaml.safe_load(open('$file'))" || {
                echo "ERRO: $file contem YAML invalido"
                exit 1
              }
              
              echo "[OK] $file esta limpo e valido"
            fi
          done
          
          echo "Todos os arquivos passaram na validacao!"